import { Track, Playlist } from '@/types/music';

export const HINDI_TRENDING_TRACKS: Track[] = [
  {
    id: 'hindi-1',
    title: 'Kesariya',
    artist: 'Arijit Singh, Pritam',
    album: 'Brahmastra',
    genre: 'Bollywood',
    duration: 268,
    youtubeId: 'BddP6PYo2gs',
    coverUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'hindi-2',
    title: 'Apna Bana Le',
    artist: 'Arijit Singh, Sachin-Jigar',
    album: 'Bhediya',
    genre: 'Bollywood',
    duration: 261,
    youtubeId: 'ElZfdU54Cp8',
    coverUrl: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'hindi-3',
    title: 'Tum Hi Ho',
    artist: 'Arijit Singh, Mithoon',
    album: 'Aashiqui 2',
    genre: 'Bollywood',
    duration: 262,
    youtubeId: 'IJq0yyWug1k',
    coverUrl: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'hindi-4',
    title: 'Chaleya',
    artist: 'Arijit Singh, Shilpa Rao',
    album: 'Jawan',
    genre: 'Bollywood',
    duration: 200,
    youtubeId: 'VAdGW7QDJiU',
    coverUrl: 'https://images.unsplash.com/photo-1550684848-fac1c5b4e853?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'hindi-5',
    title: 'Raataan Lambiyan',
    artist: 'Jubin Nautiyal, Asees Kaur',
    album: 'Shershaah',
    genre: 'Bollywood',
    duration: 230,
    youtubeId: 'gvyUuxdRdR4',
    coverUrl: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'hindi-6',
    title: 'Tere Vaste',
    artist: 'Varun Jain, Sachin-Jigar',
    album: 'Zara Hatke Zara Bachke',
    genre: 'Bollywood',
    duration: 189,
    youtubeId: 'K93Tz6T7Z2E',
    coverUrl: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'hindi-7',
    title: 'Deva Deva',
    artist: 'Arijit Singh, Jonita Gandhi',
    album: 'Brahmastra',
    genre: 'Bollywood',
    duration: 279,
    youtubeId: 'mNuhKUOD_g0',
    coverUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'hindi-8',
    title: 'Satranga',
    artist: 'Arijit Singh, Shreyas Puranik',
    album: 'ANIMAL',
    genre: 'Bollywood',
    duration: 271,
    youtubeId: 'hr3tsU2X6N4',
    coverUrl: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?auto=format&fit=crop&w=600&q=80',
  },
];

export const BILLBOARD_TOP_TRACKS: Track[] = [
  {
    id: 'global-1',
    title: 'Blinding Lights',
    artist: 'The Weeknd',
    album: 'After Hours',
    genre: 'Pop / Synthwave',
    duration: 200,
    youtubeId: '4NRXx6U8ABQ',
    coverUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'global-2',
    title: 'As It Was',
    artist: 'Harry Styles',
    album: "Harry's House",
    genre: 'Indie Pop',
    duration: 167,
    youtubeId: 'H5v3kku4y6Q',
    coverUrl: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'global-3',
    title: 'Starboy',
    artist: 'The Weeknd ft. Daft Punk',
    album: 'Starboy',
    genre: 'R&B / Electro',
    duration: 230,
    youtubeId: '34Na4j8AVgA',
    coverUrl: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'global-4',
    title: 'Shape of You',
    artist: 'Ed Sheeran',
    album: '÷ (Divide)',
    genre: 'Pop',
    duration: 233,
    youtubeId: 'JGwWNGJdvx8',
    coverUrl: 'https://images.unsplash.com/photo-1550684848-fac1c5b4e853?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'global-5',
    title: 'Levitating',
    artist: 'Dua Lipa',
    album: 'Future Nostalgia',
    genre: 'Disco Pop',
    duration: 203,
    youtubeId: 'TUVcZfQe-Kw',
    coverUrl: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'global-6',
    title: 'Save Your Tears',
    artist: 'The Weeknd',
    album: 'After Hours',
    genre: 'Synthpop',
    duration: 215,
    youtubeId: 'XXYlFuWEuKI',
    coverUrl: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'global-7',
    title: 'Flowers',
    artist: 'Miley Cyrus',
    album: 'Endless Summer Vacation',
    genre: 'Pop',
    duration: 200,
    youtubeId: 'G7KNmW9a75Y',
    coverUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=600&q=80',
  },
];

export const PUNJABI_VIRAL_TRACKS: Track[] = [
  {
    id: 'punjabi-1',
    title: 'Pasoori',
    artist: 'Ali Sethi x Shae Gill',
    album: 'Coke Studio Season 14',
    genre: 'Punjabi Fusion',
    duration: 224,
    youtubeId: '5Eqb_-j3FDA',
    coverUrl: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'punjabi-2',
    title: 'Elevated',
    artist: 'Shubh',
    album: 'Elevated Single',
    genre: 'Punjabi Hip-Hop',
    duration: 201,
    youtubeId: 'w2V_M1b_aT8',
    coverUrl: 'https://images.unsplash.com/photo-1550684848-fac1c5b4e853?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'punjabi-3',
    title: 'Lover',
    artist: 'Diljit Dosanjh',
    album: 'MoonChild Era',
    genre: 'Punjabi Pop',
    duration: 190,
    youtubeId: 'm4m58bE0Bxs',
    coverUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'punjabi-4',
    title: 'Softly',
    artist: 'Karan Aujla, Ikky',
    album: 'Making Memories',
    genre: 'Punjabi R&B',
    duration: 154,
    youtubeId: 'cWMxCE2XA9U',
    coverUrl: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?auto=format&fit=crop&w=600&q=80',
  },
];

export const LOFI_CHILL_BEATS: Track[] = [
  {
    id: 'lofi-1',
    title: 'Lofi Girl - Beats to Relax / Study to',
    artist: 'Lofi Girl',
    album: 'Midnight Study Sessions',
    genre: 'Lofi Chill',
    duration: 180,
    youtubeId: 'jfKfPfyJRdk',
    coverUrl: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'lofi-2',
    title: 'Cozy Rain Lofi Hip Hop',
    artist: 'ChilledCow',
    album: 'Rainy Night Beats',
    genre: 'Lofi Ambient',
    duration: 210,
    youtubeId: '5qap5aO4i9A',
    coverUrl: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'lofi-3',
    title: 'Coffee Shop Lofi Chill',
    artist: 'Chillhop Music',
    album: 'Lazy Afternoon',
    genre: 'Lofi Jazz',
    duration: 195,
    youtubeId: 'lTRiuFIWV54',
    coverUrl: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=600&q=80',
  },
];

export const FEATURED_PLAYLISTS: Playlist[] = [
  {
    id: 'pl-hindi',
    title: 'Trending Bollywood Hits',
    description: 'Top chart-topping Hindi romantic and party tracks featuring Arijit Singh & Pritam.',
    coverUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=600&q=80',
    _count: { tracks: HINDI_TRENDING_TRACKS.length },
    tracks: HINDI_TRENDING_TRACKS.map((t, idx) => ({
      id: `pt-hindi-${idx}`,
      playlistId: 'pl-hindi',
      trackId: t.id,
      position: idx,
      addedAt: new Date(),
      track: t,
    })),
  },
  {
    id: 'pl-billboard',
    title: 'Global Billboard Hot 100',
    description: 'The biggest international pop, synthwave, and R&B hits dominating global charts.',
    coverUrl: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?auto=format&fit=crop&w=600&q=80',
    _count: { tracks: BILLBOARD_TOP_TRACKS.length },
    tracks: BILLBOARD_TOP_TRACKS.map((t, idx) => ({
      id: `pt-billboard-${idx}`,
      playlistId: 'pl-billboard',
      trackId: t.id,
      position: idx,
      addedAt: new Date(),
      track: t,
    })),
  },
  {
    id: 'pl-punjabi',
    title: 'Punjabi Viral Hits',
    description: 'High energy Punjabi beats, hip-hop fusion, and viral anthems.',
    coverUrl: 'https://images.unsplash.com/photo-1550684848-fac1c5b4e853?auto=format&fit=crop&w=600&q=80',
    _count: { tracks: PUNJABI_VIRAL_TRACKS.length },
    tracks: PUNJABI_VIRAL_TRACKS.map((t, idx) => ({
      id: `pt-punjabi-${idx}`,
      playlistId: 'pl-punjabi',
      trackId: t.id,
      position: idx,
      addedAt: new Date(),
      track: t,
    })),
  },
  {
    id: 'pl-lofi',
    title: 'Lo-Fi Chill & Focus Beats',
    description: 'Relaxing ambient beats, vinyl warmth, and study background soundscapes.',
    coverUrl: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?auto=format&fit=crop&w=600&q=80',
    _count: { tracks: LOFI_CHILL_BEATS.length },
    tracks: LOFI_CHILL_BEATS.map((t, idx) => ({
      id: `pt-lofi-${idx}`,
      playlistId: 'pl-lofi',
      trackId: t.id,
      position: idx,
      addedAt: new Date(),
      track: t,
    })),
  },
];

export const ALL_INITIAL_TRACKS: Track[] = [
  ...HINDI_TRENDING_TRACKS,
  ...BILLBOARD_TOP_TRACKS,
  ...PUNJABI_VIRAL_TRACKS,
  ...LOFI_CHILL_BEATS,
];
